***MEAL Indicator Performance And Data Quality Dashboard***

Installation/importation of required libraries including; pandas-imports, cleans & analyzes indicator datasets in tabular, numpy-supports numerical calculations, plotly-create interactive charts, streamlit-build the dashboard interface and openpyxl-read excel files. All will support through the MEAL dashboard development process.

In [ ]:
%pip install pandas numpy plotly streamlit openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (5.24.1)
Collecting streamlit
  Downloading streamlit-1.66.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: pillow<14,>=9.2.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow!=25.0.0,<27,>=10.0.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.54.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<18,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.27.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.20)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.10.23)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.4)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.9.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading streamlit-1.66.1-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 40.6 MB/s  0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 82.5 MB/s  0:00:00
Installing collected packages: pydeck, streamlit
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [streamlit]
Successfully installed pydeck-0.9.3 streamlit-1.66.1

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import streamlit as st

print("All required libraries imported successfully!")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

All required libraries imported successfully!
Pandas version: 2.2.3
NumPy version: 2.1.3

The code cell below runs 8 fictional indicators having illustrative values across 4 quarters covering indicator name, quarterly target/annual target and actual achievements.

In [ ]:
import pandas as pd
import numpy as np

# Define the annual indicator targets
indicators = {
    "Children enrolled in school": {
        "annual_target": 2000,
        "quarterly_targets": [500, 500, 500, 500],
        "actuals": [450, 480, 520, 490]
    },
    "Households receiving support": {
        "annual_target": 1200,
        "quarterly_targets": [300, 300, 300, 300],
        "actuals": [315, 280, 310, 320]
    },
    "Farmers trained": {
        "annual_target": 800,
        "quarterly_targets": [200, 200, 200, 200],
        "actuals": [120, 180, 210, 190]
    },
    "Water points rehabilitated": {
        "annual_target": 80,
        "quarterly_targets": [20, 20, 20, 20],
        "actuals": [18, 22, 15, 20]
    },
    "Children receiving nutrition services": {
        "annual_target": 1600,
        "quarterly_targets": [400, 400, 400, 400],
        "actuals": [380, 410, 390, 420]
    },
    "Teachers trained": {
        "annual_target": 400,
        "quarterly_targets": [100, 100, 100, 100],
        "actuals": [95, 105, 90, 110]
    },
    "Households accessing clean water": {
        "annual_target": 1000,
        "quarterly_targets": [250, 250, 250, 250],
        "actuals": [200, 240, 260, 230]
    },
    "Community groups established": {
        "annual_target": 60,
        "quarterly_targets": [15, 15, 15, 15],
        "actuals": [12, 16, 14, 18]
    }
}

# Convert the information into quarterly records
records = []

for indicator_name, details in indicators.items():
    for i, quarter in enumerate(["Q1", "Q2", "Q3", "Q4"]):
        records.append({
            "indicator_name": indicator_name,
            "reporting_period": quarter,
            "quarterly_target": details["quarterly_targets"][i],
            "actual": details["actuals"][i],
            "annual_target": details["annual_target"]
        })

df = pd.DataFrame(records)

print("Dataset created successfully.")
print("Number of indicators:", df["indicator_name"].nunique())
print("Number of quarterly records:", len(df))

df.head(10)

Dataset created successfully.
Number of indicators: 8
Number of quarterly records: 32

,indicator_name,reporting_period,quarterly_target,actual,annual_target
0,Children enrolled in school,Q1,500,450,2000
1,Children enrolled in school,Q2,500,480,2000
2,Children enrolled in school,Q3,500,520,2000
3,Children enrolled in school,Q4,500,490,2000
4,Households receiving support,Q1,300,315,1200
5,Households receiving support,Q2,300,280,1200
6,Households receiving support,Q3,300,310,1200
7,Households receiving support,Q4,300,320,1200
8,Farmers trained,Q1,200,120,800
9,Farmers trained,Q2,200,180,800

The code below calculates the quarterly indicator performance and whetehr each indicator achieved it's target.

In [ ]:
# Calculate quarterly achievement percentage
df["achievement_pct"] = (
    df["actual"] / df["quarterly_target"]
) * 100

# Calculate quarterly performance gap
df["performance_gap"] = (
    df["quarterly_target"] - df["actual"]
)

# Display quarterly results
df[[
    "indicator_name",
    "reporting_period",
    "quarterly_target",
    "actual",
    "achievement_pct",
    "performance_gap"
]].round(2)

,indicator_name,reporting_period,quarterly_target,actual,achievement_pct,performance_gap
0,Children enrolled in school,Q1,500,450,90.00,50
1,Children enrolled in school,Q2,500,480,96.00,20
2,Children enrolled in school,Q3,500,520,104.00,-20
3,Children enrolled in school,Q4,500,490,98.00,10
4,Households receiving support,Q1,300,315,105.00,-15
5,Households receiving support,Q2,300,280,93.33,20
6,Households receiving support,Q3,300,310,103.33,-10
7,Households receiving support,Q4,300,320,106.67,-20
8,Farmers trained,Q1,200,120,60.00,80
9,Farmers trained,Q2,200,180,90.00,20
10,Farmers trained,Q3,200,210,105.00,-10
11,Farmers trained,Q4,200,190,95.00,10
12,Water points rehabilitated,Q1,20,18,90.00,2
13,Water points rehabilitated,Q2,20,22,110.00,-2
14,Water points rehabilitated,Q3,20,15,75.00,5
15,Water points rehabilitated,Q4,20,20,100.00,0
16,Children receiving nutrition services,Q1,400,380,95.00,20
17,Children receiving nutrition services,Q2,400,410,102.50,-10
18,Children receiving nutrition services,Q3,400,390,97.50,10
19,Children receiving nutrition services,Q4,400,420,105.00,-20
20,Teachers trained,Q1,100,95,95.00,5
21,Teachers trained,Q2,100,105,105.00,-5
22,Teachers trained,Q3,100,90,90.00,10
23,Teachers trained,Q4,100,110,110.00,-10
24,Households accessing clean water,Q1,250,200,80.00,50
25,Households accessing clean water,Q2,250,240,96.00,10
26,Households accessing clean water,Q3,250,260,104.00,-10
27,Households accessing clean water,Q4,250,230,92.00,20
28,Community groups established,Q1,15,12,80.00,3
29,Community groups established,Q2,15,16,106.67,-1
30,Community groups established,Q3,15,14,93.33,1
31,Community groups established,Q4,15,18,120.00,-3

We'll proceed to calculate the annual performance and establish the variance per indicator hereunder.The annual target and actual are the sum of the quarterly targets and actuals respectively.

In [ ]:
# Aggregate quarterly results into annual totals
annual_df = (
    df.groupby(
        ["indicator_name", "annual_target"],
        as_index=False
    )
    .agg(
        annual_actual=("actual", "sum"),
        total_quarterly_target=("quarterly_target", "sum")
    )
)

# Calculate annual achievement and performance gap
annual_df["annual_achievement_pct"] = (
    annual_df["annual_actual"] / annual_df["annual_target"]
) * 100

annual_df["annual_performance_gap"] = (
    annual_df["annual_target"] - annual_df["annual_actual"]
)

# Display annual performance
annual_df[[
    "indicator_name",
    "annual_target",
    "annual_actual",
    "annual_achievement_pct",
    "annual_performance_gap"
]].round(2)

,indicator_name,annual_target,annual_actual,annual_achievement_pct,annual_performance_gap
0,Children enrolled in school,2000,1940,97.00,60
1,Children receiving nutrition services,1600,1600,100.00,0
2,Community groups established,60,60,100.00,0
3,Farmers trained,800,700,87.50,100
4,Households accessing clean water,1000,930,93.00,70
5,Households receiving support,1200,1225,102.08,-25
6,Teachers trained,400,400,100.00,0
7,Water points rehabilitated,80,75,93.75,5

**Section Two:**
This section involves developing classes including; Indicator(stores the indicator name, reporting period, target and actual achievements), Dataqualitychecker(Performs validation checks and identifies data quality issues such as missing values, duplicate records, invalid entries among others), PerformanceAnalyze(Calculates achievements, performance gaps and assigns status classifications using defined thresholds) and ReportGenerator(Produces summary visualisations and downloadable analysis reports)

**2.1. The Indicator Class**

In [ ]:
class Indicator:
    """Represent a MEAL indicator for a reporting period."""

    def __init__(
        self,
        indicator_name,
        reporting_period,
        target,
        actual,
        annual_target
    ):
        """Initialise an indicator with its target and actual values."""

        # Validate the indicator name
        if not isinstance(indicator_name, str) or not indicator_name.strip():
            raise ValueError("Indicator name must not be empty.")

        # Validate the reporting period
        valid_periods = ["Q1", "Q2", "Q3", "Q4"]

        if reporting_period not in valid_periods:
            raise ValueError("Reporting period must be Q1, Q2, Q3 or Q4.")

        # Validate numerical values
        for field_name, value in {
            "target": target,
            "actual": actual,
            "annual_target": annual_target
        }.items():
            if isinstance(value, (bool, np.bool_)) or not isinstance(
                value, (int, float, np.integer, np.floating)
            ):
                raise TypeError(f"{field_name} must be numeric.")

            if not np.isfinite(value):
                raise ValueError(f"{field_name} must be finite.")

            if value < 0:
                raise ValueError(f"{field_name} cannot be negative.")

        if target <= 0:
            raise ValueError("Quarterly target must be greater than zero.")

        if annual_target <= 0:
            raise ValueError("Annual target must be greater than zero.")

        # Store the validated data
        self._indicator_name = indicator_name.strip()
        self._reporting_period = reporting_period
        self._target = float(target)
        self._actual = float(actual)
        self._annual_target = float(annual_target)

    @property
    def indicator_name(self):
        """Return the indicator name."""
        return self._indicator_name

    @property
    def reporting_period(self):
        """Return the reporting period."""
        return self._reporting_period

    @property
    def target(self):
        """Return the quarterly target."""
        return self._target

    @property
    def actual(self):
        """Return the actual achievement."""
        return self._actual

    @property
    def annual_target(self):
        """Return the annual target."""
        return self._annual_target

    def calculate_achievement(self):
        """Calculate achievement as a percentage of the quarterly target."""
        return (self.actual / self.target) * 100

    def calculate_performance_gap(self):
        """Calculate the difference between target and actual achievement."""
        return self.target - self.actual

    def to_dict(self):
        """Return indicator details as a dictionary."""
        return {
            "indicator_name": self.indicator_name,
            "reporting_period": self.reporting_period,
            "quarterly_target": self.target,
            "actual": self.actual,
            "annual_target": self.annual_target,
            "achievement_pct": self.calculate_achievement(),
            "performance_gap": self.calculate_performance_gap()
        }

**Testing the above indicator class**

In [ ]:
# Create an indicator object using our sample data
indicator = Indicator(
    indicator_name="Children enrolled in school",
    reporting_period="Q1",
    target=500,
    actual=450,
    annual_target=2000
)

# Display the indicator details
print("Indicator:", indicator.indicator_name)
print("Reporting period:", indicator.reporting_period)
print("Quarterly target:", indicator.target)
print("Actual achievement:", indicator.actual)
print("Annual target:", indicator.annual_target)
print("Achievement rate:", round(indicator.calculate_achievement(), 2), "%")
print("Performance gap:", indicator.calculate_performance_gap())

Indicator: Children enrolled in school
Reporting period: Q1
Quarterly target: 500.0
Actual achievement: 450.0
Annual target: 2000.0
Achievement rate: 90.0 %
Performance gap: 50.0

**Testing the validation criteria, actual can not be negative and there is no Q5**

In [ ]:
# Test an invalid reporting period
try:
    invalid_indicator = Indicator(
        "Farmers trained", "Q5", 200, 150, 800
    )
except ValueError as error:
    print("Validation successful:", error)

# Test a negative actual achievement
try:
    invalid_indicator = Indicator(
        "Farmers trained", "Q1", 200, -10, 800
    )
except ValueError as error:
    print("Validation successful:", error)

Validation successful: Reporting period must be Q1, Q2, Q3 or Q4.
Validation successful: actual cannot be negative.

**2.2: DataQualityChecker Class**

This class will check for missing values, invalid entries, duplicate records among other data quality issues

In [ ]:

class DataQualityChecker:
    """Check MEAL indicator datasets for common data quality issues."""

    REQUIRED_COLUMNS = [
        "indicator_name",
        "reporting_period",
        "quarterly_target",
        "actual",
        "annual_target"
    ]

    VALID_PERIODS = ["Q1", "Q2", "Q3", "Q4"]

    def __init__(self, data):
        """Initialise the checker with a copy of the supplied dataset."""
        if not isinstance(data, pd.DataFrame):
            raise TypeError("Input data must be a pandas DataFrame.")

        self.data = data.copy()
        self.issues = pd.DataFrame()

    def check_columns(self):
        """Check that all required columns are present."""
        missing_columns = [
            column for column in self.REQUIRED_COLUMNS
            if column not in self.data.columns
        ]

        if missing_columns:
            raise ValueError(
                f"Missing required columns: {missing_columns}"
            )

        return True

    def check_missing_values(self):
        """Identify missing values in required fields."""
        self.check_columns()

        missing = self.data[
            self.data[self.REQUIRED_COLUMNS].isna().any(axis=1)
        ].copy()

        if not missing.empty:
            missing["issue"] = "Missing required value"

        return missing

    def check_duplicates(self):
        """Identify repeated indicator-period records."""
        self.check_columns()

        duplicates = self.data[
            self.data.duplicated(
                subset=["indicator_name", "reporting_period"],
                keep=False
            )
        ].copy()

        if not duplicates.empty:
            duplicates["issue"] = "Duplicate indicator-period record"

        return duplicates

    def check_invalid_values(self):
        """Identify invalid periods and invalid numerical values."""
        self.check_columns()
        findings = []

        for index, row in self.data.iterrows():
            period = row["reporting_period"]

            if pd.notna(period) and period not in self.VALID_PERIODS:
                findings.append({
                    "row_index": index,
                    "indicator_name": row["indicator_name"],
                    "reporting_period": period,
                    "issue": "Invalid reporting period"
                })

            for column in [
                "quarterly_target", "actual", "annual_target"
            ]:
                value = row[column]

                if pd.isna(value):
                    continue

                if isinstance(value, (bool, np.bool_)) or not isinstance(
                    value, (int, float, np.integer, np.floating)
                ):
                    findings.append({
                        "row_index": index,
                        "indicator_name": row["indicator_name"],
                        "reporting_period": period,
                        "issue": f"Non-numeric value in {column}"
                    })
                    continue

                if not np.isfinite(value):
                    findings.append({
                        "row_index": index,
                        "indicator_name": row["indicator_name"],
                        "reporting_period": period,
                        "issue": f"Non-finite value in {column}"
                    })
                    continue

                if value < 0:
                    findings.append({
                        "row_index": index,
                        "indicator_name": row["indicator_name"],
                        "reporting_period": period,
                        "issue": f"Negative value in {column}"
                    })

                if column in [
                    "quarterly_target", "annual_target"
                ] and value == 0:
                    findings.append({
                        "row_index": index,
                        "indicator_name": row["indicator_name"],
                        "reporting_period": period,
                        "issue": f"Zero value in {column}"
                    })

        return pd.DataFrame(findings)

    def check_annual_target_consistency(self):
        """Identify indicators with inconsistent annual targets."""
        self.check_columns()

        valid_targets = self.data.dropna(
            subset=["indicator_name", "annual_target"]
        )

        target_counts = valid_targets.groupby(
            "indicator_name"
        )["annual_target"].nunique()

        inconsistent_names = target_counts[
            target_counts > 1
        ].index

        inconsistent = valid_targets[
            valid_targets["indicator_name"].isin(inconsistent_names)
        ].copy()

        if not inconsistent.empty:
            inconsistent["issue"] = "Inconsistent annual target"

        return inconsistent

    def run_all_checks(self):
        """Run all data quality checks and return a summary."""
        self.check_columns()

        missing = self.check_missing_values()
        duplicates = self.check_duplicates()
        invalid = self.check_invalid_values()
        inconsistent = self.check_annual_target_consistency()

        self.issues = pd.concat(
            [
                missing,
                duplicates,
                invalid,
                inconsistent
            ],
            ignore_index=True,
            sort=False
        )

        return {
            "records_checked": len(self.data),
            "missing_value_rows": len(missing),
            "duplicate_rows": len(duplicates),
            "invalid_value_issues": len(invalid),
            "inconsistent_target_rows": len(inconsistent),
            "total_issues": len(self.issues),
            "issues": self.issues
        }

**Testing the class against the existing dataset**

In [ ]:
checker = DataQualityChecker(df)

quality_results = checker.run_all_checks()

print("Records checked:", quality_results["records_checked"])
print("Rows with missing values:", quality_results["missing_value_rows"])
print("Duplicate rows:", quality_results["duplicate_rows"])
print("Invalid value issues:", quality_results["invalid_value_issues"])
print("Inconsistent annual target rows:", quality_results["inconsistent_target_rows"])
print("Total issues:", quality_results["total_issues"])

Records checked: 32
Rows with missing values: 0
Duplicate rows: 0
Invalid value issues: 0
Inconsistent annual target rows: 0
Total issues: 0

**Testing whether the DataQualityChecker class ably detects issues by intentionally introducing a dataset entailing some data quality issues as coded below;**

In [ ]:
# Make a separate copy for testing.
# The original df remains unchanged.
test_df = df.copy()

# Introduce a missing actual achievement
test_df.loc[0, "actual"] = np.nan

# Introduce a duplicate indicator-quarter record
test_df = pd.concat(
    [test_df, test_df.iloc[[1]]],
    ignore_index=True
)

# Introduce an invalid negative target
test_df.loc[3, "quarterly_target"] = -20

# Introduce an invalid reporting period
test_df.loc[4, "reporting_period"] = "Q5"

# Introduce an inconsistent annual target
test_df.loc[8, "annual_target"] = 2500

# Run the checks
test_checker = DataQualityChecker(test_df)
test_results = test_checker.run_all_checks()

print("Records checked:", test_results["records_checked"])
print("Rows with missing values:", test_results["missing_value_rows"])
print("Duplicate rows:", test_results["duplicate_rows"])
print("Invalid value issues:", test_results["invalid_value_issues"])
print("Inconsistent annual target rows:", test_results["inconsistent_target_rows"])
print("Total issues:", test_results["total_issues"])

Records checked: 33
Rows with missing values: 1
Duplicate rows: 2
Invalid value issues: 2
Inconsistent annual target rows: 4
Total issues: 9

The findings indicate of the 33 checked records, 1 row has missing values, 2 duplicate rows, invalid value & inconsistent annual targets are 2 and 4 respectively. This implies the class is functional. The details of the issues are highlighted in the tabular code below.

In [ ]:
test_results["issues"]

,indicator_name,reporting_period,quarterly_target,actual,annual_target,achievement_pct,performance_gap,issue,row_index
0,Children enrolled in school,Q1,500.0,NaN,2000.0,90.0,50.0,Missing required value,NaN
1,Children enrolled in school,Q2,500.0,480.0,2000.0,96.0,20.0,Duplicate indicator-period record,NaN
2,Children enrolled in school,Q2,500.0,480.0,2000.0,96.0,20.0,Duplicate indicator-period record,NaN
3,Children enrolled in school,Q4,NaN,NaN,NaN,NaN,NaN,Negative value in quarterly_target,3.0
4,Households receiving support,Q5,NaN,NaN,NaN,NaN,NaN,Invalid reporting period,4.0
5,Farmers trained,Q1,200.0,120.0,2500.0,60.0,80.0,Inconsistent annual target,NaN
6,Farmers trained,Q2,200.0,180.0,800.0,90.0,20.0,Inconsistent annual target,NaN
7,Farmers trained,Q3,200.0,210.0,800.0,105.0,-10.0,Inconsistent annual target,NaN
8,Farmers trained,Q4,200.0,190.0,800.0,95.0,10.0,Inconsistent annual target,NaN

The class identified inconsistent annual targets i.e 2500 and 800 for the same indicator (Farmers trained), indicator children enrolled in school has a missing target in Q1 and is duplicated in Q2 with a negative target in Q4 and finally indicator Households receiving support had an invalid reproting quarter (Q5).

**2.3: PerformanceAnalyzer** **Class**

This class will calculate quarterly achievements, performance gaps and clasify performance as on track, needs improvement and off-track as in the thresholds;
1. 90% and above .........On track
2. 70% to below 90% ......Needs Improvement
3. Below 70% .......... Off-track

In [ ]:
class PerformanceAnalyzer:
    """Analyse quarterly and annual MEAL indicator performance."""

    def __init__(self, data, on_track_threshold=90,
                 attention_threshold=70):

        if not isinstance(data, pd.DataFrame):
            raise TypeError("Input data must be a pandas DataFrame.")

        if not (0 <= attention_threshold < on_track_threshold
                and on_track_threshold <= 100):
            raise ValueError(
                "Thresholds must satisfy 0 <= attention < on_track <= 100."
            )

        self.data = data.copy()
        self.on_track_threshold = on_track_threshold
        self.attention_threshold = attention_threshold

        self.required_columns = [
            "indicator_name",
            "reporting_period",
            "quarterly_target",
            "actual",
            "annual_target"
        ]

        missing_columns = [
            col for col in self.required_columns
            if col not in self.data.columns
        ]

        if missing_columns:
            raise ValueError(
                f"Missing required columns: {missing_columns}"
            )

    def _prepare_valid_data(self):
        """Keep records suitable for performance calculations."""

        data = self.data.copy()

        numeric_columns = [
            "quarterly_target",
            "actual",
            "annual_target"
        ]

        for col in numeric_columns:
            data[col] = pd.to_numeric(data[col], errors="coerce")

        valid = (
            data["indicator_name"].notna()
            & data["indicator_name"].astype(str).str.strip().ne("")
            & data["reporting_period"].isin(["Q1", "Q2", "Q3", "Q4"])
            & data[numeric_columns].notna().all(axis=1)
            & np.isfinite(data[numeric_columns]).all(axis=1)
            & data["quarterly_target"].gt(0)
            & data["annual_target"].gt(0)
            & data["actual"].ge(0)
        )

        return data.loc[valid].copy()

    def classify_performance(self, achievement_pct):
        """Classify performance using the project's thresholds."""

        if pd.isna(achievement_pct):
            return "Data Unavailable"

        if achievement_pct >= self.on_track_threshold:
            return "On Track"

        if achievement_pct >= self.attention_threshold:
            return "Needs Improvement"

        return "Off Track"

    def analyze_quarterly_performance(self):
        """Calculate achievement, gaps and status for each quarter."""

        result = self._prepare_valid_data()

        result["achievement_pct"] = (
            result["actual"] / result["quarterly_target"]
        ) * 100

        result["performance_gap"] = (
            result["quarterly_target"] - result["actual"]
        )

        result["performance_status"] = (
            result["achievement_pct"].apply(self.classify_performance)
        )

        return result

    def analyze_annual_performance(self):
        """Summarise annual actuals and assess annual performance."""

        quarterly = self._prepare_valid_data()

        annual = (
            quarterly.groupby("indicator_name", as_index=False)
            .agg(
                annual_target=("annual_target", "first"),
                annual_actual=("actual", "sum"),
                reported_quarters=("reporting_period", "nunique"),
                annual_targets_reported=("annual_target", "nunique")
            )
        )

        annual["data_status"] = np.where(
            (annual["reported_quarters"] == 4)
            & (annual["annual_targets_reported"] == 1),
            "Complete",
            "Review Required"
        )

        annual["annual_achievement_pct"] = (
            annual["annual_actual"] / annual["annual_target"]
        ) * 100

        annual["annual_performance_gap"] = (
            annual["annual_target"] - annual["annual_actual"]
        )

        annual["performance_status"] = (
            annual["annual_achievement_pct"].apply(
                self.classify_performance
            )
        )

        annual.loc[
            annual["data_status"] != "Complete",
            "performance_status"
        ] = "Review Required"

        return annual

    def get_indicators_requiring_attention(self):
        """Return quarterly indicators needing improvement or off track."""

        quarterly = self.analyze_quarterly_performance()

        return quarterly[
            quarterly["performance_status"].isin(
                ["Needs Improvement", "Off Track"]
            )
        ].copy()

    def get_quarterly_summary(self):
        """Summarise performance status counts by quarter."""

        quarterly = self.analyze_quarterly_performance()

        summary = (
            quarterly.groupby("reporting_period", as_index=False)
            .agg(
                indicators_reported=("indicator_name", "count"),
                average_achievement_pct=("achievement_pct", "mean"),
                on_track=(
                    "performance_status",
                    lambda x: (x == "On Track").sum()
                ),
                needs_improvement=(
                    "performance_status",
                    lambda x: (x == "Needs Improvement").sum()
                ),
                off_track=(
                    "performance_status",
                    lambda x: (x == "Off Track").sum()
                )
            )
        )

        quarter_order = ["Q1", "Q2", "Q3", "Q4"]

        summary["reporting_period"] = pd.Categorical(
            summary["reporting_period"],
            categories=quarter_order,
            ordered=True
        )

        return (
            summary.sort_values("reporting_period")
            .reset_index(drop=True)
        )

Testing the quarterly performance, it calculates performance for each quarter and assigns a status (on-track, needs improvement & off-track)

In [ ]:
analyzer = PerformanceAnalyzer(df)

quarterly_results = analyzer.analyze_quarterly_performance()

quarterly_results[
    [
        "indicator_name",
        "reporting_period",
        "quarterly_target",
        "actual",
        "achievement_pct",
        "performance_gap",
        "performance_status"
    ]
].round(2)

,indicator_name,reporting_period,quarterly_target,actual,achievement_pct,performance_gap,performance_status
0,Children enrolled in school,Q1,500,450,90.00,50,On Track
1,Children enrolled in school,Q2,500,480,96.00,20,On Track
2,Children enrolled in school,Q3,500,520,104.00,-20,On Track
3,Children enrolled in school,Q4,500,490,98.00,10,On Track
4,Households receiving support,Q1,300,315,105.00,-15,On Track
5,Households receiving support,Q2,300,280,93.33,20,On Track
6,Households receiving support,Q3,300,310,103.33,-10,On Track
7,Households receiving support,Q4,300,320,106.67,-20,On Track
8,Farmers trained,Q1,200,120,60.00,80,Off Track
9,Farmers trained,Q2,200,180,90.00,20,On Track
10,Farmers trained,Q3,200,210,105.00,-10,On Track
11,Farmers trained,Q4,200,190,95.00,10,On Track
12,Water points rehabilitated,Q1,20,18,90.00,2,On Track
13,Water points rehabilitated,Q2,20,22,110.00,-2,On Track
14,Water points rehabilitated,Q3,20,15,75.00,5,Needs Improvement
15,Water points rehabilitated,Q4,20,20,100.00,0,On Track
16,Children receiving nutrition services,Q1,400,380,95.00,20,On Track
17,Children receiving nutrition services,Q2,400,410,102.50,-10,On Track
18,Children receiving nutrition services,Q3,400,390,97.50,10,On Track
19,Children receiving nutrition services,Q4,400,420,105.00,-20,On Track
20,Teachers trained,Q1,100,95,95.00,5,On Track
21,Teachers trained,Q2,100,105,105.00,-5,On Track
22,Teachers trained,Q3,100,90,90.00,10,On Track
23,Teachers trained,Q4,100,110,110.00,-10,On Track
24,Households accessing clean water,Q1,250,200,80.00,50,Needs Improvement
25,Households accessing clean water,Q2,250,240,96.00,10,On Track
26,Households accessing clean water,Q3,250,260,104.00,-10,On Track
27,Households accessing clean water,Q4,250,230,92.00,20,On Track
28,Community groups established,Q1,15,12,80.00,3,Needs Improvement
29,Community groups established,Q2,15,16,106.67,-1,On Track
30,Community groups established,Q3,15,14,93.33,1,On Track
31,Community groups established,Q4,15,18,120.00,-3,On Track

Testing the annual performance (the section summarises the quarterly actuals against the annual target. An indicator is "complete" if all the four quarters are represented and annual target is consistent across dataset, otherwise it's marked "review required."

In [ ]:
annual_results = analyzer.analyze_annual_performance()

annual_results[
    [
        "indicator_name",
        "annual_target",
        "annual_actual",
        "reported_quarters",
        "annual_achievement_pct",
        "annual_performance_gap",
        "data_status",
        "performance_status"
    ]
].round(2)

,indicator_name,annual_target,annual_actual,reported_quarters,annual_achievement_pct,annual_performance_gap,data_status,performance_status
0,Children enrolled in school,2000,1940,4,97.00,60,Complete,On Track
1,Children receiving nutrition services,1600,1600,4,100.00,0,Complete,On Track
2,Community groups established,60,60,4,100.00,0,Complete,On Track
3,Farmers trained,800,700,4,87.50,100,Complete,Needs Improvement
4,Households accessing clean water,1000,930,4,93.00,70,Complete,On Track
5,Households receiving support,1200,1225,4,102.08,-25,Complete,On Track
6,Teachers trained,400,400,4,100.00,0,Complete,On Track
7,Water points rehabilitated,80,75,4,93.75,5,Complete,On Track

**Identifying indicators requiring improvement to support implementers identify where follow-up maybe required **

In [ ]:
attention_results = analyzer.get_indicators_requiring_attention()

attention_results[
    [
        "indicator_name",
        "reporting_period",
        "achievement_pct",
        "performance_gap",
        "performance_status"
    ]
].round(2)

,indicator_name,reporting_period,achievement_pct,performance_gap,performance_status
8,Farmers trained,Q1,60.0,80,Off Track
14,Water points rehabilitated,Q3,75.0,5,Needs Improvement
24,Households accessing clean water,Q1,80.0,50,Needs Improvement
28,Community groups established,Q1,80.0,3,Needs Improvement

Generating a quarterly summary

In [ ]:
quarterly_summary = analyzer.get_quarterly_summary()

quarterly_summary

,reporting_period,indicators_reported,average_achievement_pct,on_track,needs_improvement,off_track
0,Q1,8,86.875000,5,2,1
1,Q2,8,99.937500,8,0,0
2,Q3,8,96.520833,7,1,0
3,Q4,8,103.333333,8,0,0

**2.4: Creating the ReportGeneratorClass**

This class prepares analysis findings for reporting. It shows quarterly and annual performance, any data quality issues and indicators requiring follow-up

In [ ]:
class ReportGenerator:
    """Generate summary reports from MEAL performance and data-quality results."""

    def __init__(self, performance_analyzer, data_quality_checker):
        self.performance_analyzer = performance_analyzer
        self.data_quality_checker = data_quality_checker

    def generate_quarterly_report(self):
        """Return quarterly indicator performance results."""
        return self.performance_analyzer.analyze_quarterly_performance()

    def generate_annual_report(self):
        """Return annual indicator performance results."""
        return self.performance_analyzer.analyze_annual_performance()

    def generate_follow_up_report(self):
        """Return indicators needing improvement or classified off track."""
        return self.performance_analyzer.get_indicators_requiring_attention()

    def generate_data_quality_report(self):
        """Return data-quality findings and summary."""
        return self.data_quality_checker.run_all_checks()

    def generate_overall_summary(self):
        """Return key figures for a high-level MEAL performance report."""

        quarterly = self.performance_analyzer.analyze_quarterly_performance()
        annual = self.performance_analyzer.analyze_annual_performance()
        quality_summary = self.data_quality_checker.run_all_checks()

        summary = {
            "Total quarterly records analysed": len(quarterly),
            "Unique indicators": quarterly["indicator_name"].nunique(),
            "Annual indicators complete": int(
                (annual["data_status"] == "Complete").sum()
            ),
            "Annual indicators requiring review": int(
                (annual["data_status"] == "Review Required").sum()
            ),
            "Quarterly records On Track": int(
                (quarterly["performance_status"] == "On Track").sum()
            ),
            "Quarterly records Needs Improvement": int(
                (quarterly["performance_status"] == "Needs Improvement").sum()
            ),
            "Quarterly records Off Track": int(
                (quarterly["performance_status"] == "Off Track").sum()
            )
        }

        return pd.DataFrame(
            list(summary.items()),
            columns=["Measure", "Result"]
        )

This class uses the existing classes and their calculations otherthan repeating the same thus demonstrating typical encapsulation and reuse.

In [ ]:
report_generator = ReportGenerator(
    performance_analyzer=analyzer,
    data_quality_checker=checker
)

print("ReportGenerator created successfully.")

ReportGenerator created successfully.

In [ ]:
overall_summary = report_generator.generate_overall_summary()

overall_summary

                               Measure  Result
0     Total quarterly records analysed      32
1                    Unique indicators       8
2           Annual indicators complete       8
3   Annual indicators requiring review       0
4           Quarterly records On Track      28
5  Quarterly records Needs Improvement       3
6          Quarterly records Off Track       1

Generating the follow-up report which extracts indicators both off-track and those requiring improvement for implementating teams to prioritize for corrective action.

In [ ]:
follow_up_report = report_generator.generate_follow_up_report()

follow_up_report[
    [
        "indicator_name",
        "reporting_period",
        "quarterly_target",
        "actual",
        "achievement_pct",
        "performance_gap",
        "performance_status"
    ]
].round(2)

,indicator_name,reporting_period,quarterly_target,actual,achievement_pct,performance_gap,performance_status
8,Farmers trained,Q1,200,120,60.0,80,Off Track
14,Water points rehabilitated,Q3,20,15,75.0,5,Needs Improvement
24,Households accessing clean water,Q1,250,200,80.0,50,Needs Improvement
28,Community groups established,Q1,15,12,80.0,3,Needs Improvement

From the table, 4 indicators require follow-up. farmers trained is off-track given it has a performance gap of 80 whereas the other 3(water points rehabilitated, households accessing clean water and community groups established) need improvement

Exporting the report to CSV to enable donwloading

In [ ]:
quarterly_report = report_generator.generate_quarterly_report()
annual_report = report_generator.generate_annual_report()

quarterly_report.to_csv("quarterly_meal_report.csv", index=False)
annual_report.to_csv("annual_meal_report.csv", index=False)
follow_up_report.to_csv("meal_follow_up_report.csv", index=False)
overall_summary.to_csv("meal_overall_summary.csv", index=False)

print("Four MEAL reports exported successfully.")

Four MEAL reports exported successfully.

Downloading the CSV for the four reports exported

In [ ]:
from google.colab import files

files.download("quarterly_meal_report.csv")
files.download("annual_meal_report.csv")
files.download("meal_follow_up_report.csv")
files.download("meal_overall_summary.csv")

**Section 3: Building the Visual MEAL Dashboard**

Here I will use Plotly for interactive charts & visual dashboard foundation before linking the analysis to Streamlit interface

I will prepare the dashboard in the code below using the existing classe which were run in the earlier codes.

In [ ]:
# Prepare data for dashboard charts
quarterly_results = analyzer.analyze_quarterly_performance()
annual_results = analyzer.analyze_annual_performance()
quarterly_summary = analyzer.get_quarterly_summary()
follow_up_report = analyzer.get_indicators_requiring_attention()

print("Dashboard data prepared successfully.")
print("Quarterly records:", len(quarterly_results))
print("Annual indicators:", len(annual_results))
print("Follow-up records:", len(follow_up_report))

Dashboard data prepared successfully.
Quarterly records: 32
Annual indicators: 8
Follow-up records: 4

Creating the key performance indicators which will be visible  or display on the dashboard and these include; Number of indicators monitored, Average Annual Achievement, Indicators on track, off-track and those requiring improvement among others in the code below.

In [ ]:
total_indicators = annual_results["indicator_name"].nunique()

overall_annual_achievement = (
    annual_results.loc[
        annual_results["data_status"] == "Complete",
        "annual_achievement_pct"
    ].mean()
)

on_track_count = (
    quarterly_results["performance_status"] == "On Track"
).sum()

needs_improvement_count = (
    quarterly_results["performance_status"] == "Needs Improvement"
).sum()

off_track_count = (
    quarterly_results["performance_status"] == "Off Track"
).sum()

print("MEAL DASHBOARD — KEY INDICATORS")
print("--------------------------------")
print("Indicators monitored:", total_indicators)
print("Average annual achievement:", round(overall_annual_achievement, 2), "%")
print("Quarterly records On Track:", on_track_count)
print("Quarterly records Needs Improvement:", needs_improvement_count)
print("Quarterly records Off Track:", off_track_count)

MEAL DASHBOARD — KEY INDICATORS
--------------------------------
Indicators monitored: 8
Average annual achievement: 96.67 %
Quarterly records On Track: 28
Quarterly records Needs Improvement: 3
Quarterly records Off Track: 1

The section below visualizes the quarterly average performance

In [ ]:
import plotly.express as px

fig = px.line(
    quarterly_summary,
    x="reporting_period",
    y="average_achievement_pct",
    markers=True,
    title="Average MEAL Indicator Achievement by Quarter",
    labels={
        "reporting_period": "Reporting Quarter",
        "average_achievement_pct": "Average Achievement (%)"
    }
)

fig.update_layout(
    yaxis_title="Average Achievement (%)",
    xaxis_title="Reporting Quarter",
    template="plotly_white"
)

fig.show()

In [ ]:
status_summary = (
    quarterly_results.groupby(
        ["reporting_period", "performance_status"],
        observed=True
    )
    .size()
    .reset_index(name="number_of_records")
)

# Assign a distinct colour to each performance status
status_colors = {
    "On Track": "green",
    "Needs Improvement": "orange",
    "Off Track": "red"
}

fig = px.bar(
    status_summary,
    x="reporting_period",
    y="number_of_records",
    color="performance_status",
    barmode="stack",
    title="Quarterly Indicator Performance Status",
    labels={
        "reporting_period": "Reporting Quarter",
        "number_of_records": "Number of Indicators",
        "performance_status": "Performance Status"
    },
    color_discrete_map=status_colors,
    category_orders={
        "performance_status": [
            "On Track",
            "Needs Improvement",
            "Off Track"
        ],
        "reporting_period": ["Q1", "Q2", "Q3", "Q4"]
    }
)

fig.update_layout(
    template="plotly_white",
    legend_title_text="Performance Status",
    xaxis_title="Reporting Quarter",
    yaxis_title="Number of Indicators",
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="center",
        x=0.5
    )
)

fig.show()

The chart above, visualizes the performances status per tracker;
On-track is represented by green (for 90% and above achievements), Needs improvement in Orange (from 70% to below 90% achievement) and off-track red (<70% achievement).

In [ ]:
fig = px.bar(
    annual_results,
    x="indicator_name",
    y="annual_achievement_pct",
    color="performance_status",
    title="Annual Indicator Achievement (%)",
    labels={
        "indicator_name": "MEAL Indicator",
        "annual_achievement_pct": "Achievement (%)",
        "performance_status": "Performance Status"
    },
    color_discrete_map={
        "On Track": "green",
        "Needs Improvement": "orange",
        "Off Track": "red",
        "Review Required": "gray",
        "Data Unavailable": "black"
    },
    category_orders={
        "performance_status": [
            "On Track",
            "Needs Improvement",
            "Off Track",
            "Review Required",
            "Data Unavailable"
        ]
    },
    hover_data=[
        "annual_target",
        "annual_actual",
        "annual_performance_gap",
        "data_status"
    ]
)

fig.add_hline(
    y=90,
    line_dash="dash",
    line_color="green",
    annotation_text="90% On Track threshold"
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="MEAL Indicator",
    yaxis_title="Annual Achievement (%)",
    xaxis_tickangle=-35,
    legend_title_text="Performance Status"
)

fig.show()

The display in the chart above shows annual indicator performance, only one indicator (farmers trained) falls below the on-track performance threshold of 90%.

In [ ]:
follow_up_display = follow_up_report[
    [
        "indicator_name",
        "reporting_period",
        "quarterly_target",
        "actual",
        "achievement_pct",
        "performance_gap",
        "performance_status"
    ]
].copy()

follow_up_display["achievement_pct"] = (
    follow_up_display["achievement_pct"].round(2)
)

follow_up_display

,indicator_name,reporting_period,quarterly_target,actual,achievement_pct,performance_gap,performance_status
8,Farmers trained,Q1,200,120,60.0,80,Off Track
14,Water points rehabilitated,Q3,20,15,75.0,5,Needs Improvement
24,Households accessing clean water,Q1,250,200,80.0,50,Needs Improvement
28,Community groups established,Q1,15,12,80.0,3,Needs Improvement

This is a table which only displays indicators which need a follow-up; these are either off-track or needs improvement as in the details above.

***Section 4: The Interactive Dashboard***

creating the Streamlit file

In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(
    page_title="MEAL Performance Dashboard",
    page_icon="📊",
    layout="wide"
)

STATUS_COLORS = {
    "On Track": "green",
    "Needs Improvement": "orange",
    "Off Track": "red",
    "Review Required": "gray",
    "Data Unavailable": "black"
}

REQUIRED_COLUMNS = [
    "indicator_name",
    "reporting_period",
    "quarterly_target",
    "actual",
    "annual_target"
]

# --------------------------------------------------
# Sample dataset used when no file is uploaded
# --------------------------------------------------
def create_sample_data():
    indicators = {
        "Children enrolled in school": {
            "annual_target": 2000,
            "targets": [500, 500, 500, 500],
            "actuals": [450, 480, 520, 490]
        },
        "Households receiving support": {
            "annual_target": 1200,
            "targets": [300, 300, 300, 300],
            "actuals": [315, 280, 310, 320]
        },
        "Farmers trained": {
            "annual_target": 800,
            "targets": [200, 200, 200, 200],
            "actuals": [120, 180, 210, 190]
        },
        "Water points rehabilitated": {
            "annual_target": 80,
            "targets": [20, 20, 20, 20],
            "actuals": [18, 22, 15, 20]
        },
        "Children receiving nutrition services": {
            "annual_target": 1600,
            "targets": [400, 400, 400, 400],
            "actuals": [380, 410, 390, 420]
        },
        "Teachers trained": {
            "annual_target": 400,
            "targets": [100, 100, 100, 100],
            "actuals": [95, 105, 90, 110]
        },
        "Households accessing clean water": {
            "annual_target": 1000,
            "targets": [250, 250, 250, 250],
            "actuals": [200, 240, 260, 230]
        },
        "Community groups established": {
            "annual_target": 60,
            "targets": [15, 15, 15, 15],
            "actuals": [12, 16, 14, 18]
        }
    }

    records = []
    for name, details in indicators.items():
        for i, quarter in enumerate(["Q1", "Q2", "Q3", "Q4"]):
            records.append({
                "indicator_name": name,
                "reporting_period": quarter,
                "quarterly_target": details["targets"][i],
                "actual": details["actuals"][i],
                "annual_target": details["annual_target"]
            })

    return pd.DataFrame(records)


def load_uploaded_file(uploaded_file):
    if uploaded_file.name.lower().endswith(".csv"):
        return pd.read_csv(uploaded_file)
    return pd.read_excel(uploaded_file)


def classify_performance(value):
    if pd.isna(value) or not np.isfinite(value):
        return "Data Unavailable"
    if value >= 90:
        return "On Track"
    if value >= 70:
        return "Needs Improvement"
    return "Off Track"


def prepare_data(raw_data):
    data = raw_data.copy()
    issues = []

    missing_columns = [
        col for col in REQUIRED_COLUMNS if col not in data.columns
    ]

    if missing_columns:
        return None, [
            "Missing required columns: " + ", ".join(missing_columns)
        ]

    # Check missing values in required fields
    for col in REQUIRED_COLUMNS:
        missing_count = int(data[col].isna().sum())
        if missing_count:
            issues.append(
                f"{col}: {missing_count} missing value(s)"
            )

    # Check duplicate indicator-quarter records
    duplicates = data.duplicated(
        subset=["indicator_name", "reporting_period"],
        keep=False
    )
    if duplicates.any():
        issues.append(
            f"{int(duplicates.sum())} row(s) belong to duplicate "
            "indicator-quarter records"
        )

    # Convert targets and actuals to numeric
    numeric_columns = [
        "quarterly_target", "actual", "annual_target"
    ]

    for col in numeric_columns:
        original = data[col].copy()
        converted = pd.to_numeric(original, errors="coerce")

        invalid_count = int(
            (original.notna() & converted.isna()).sum()
        )
        if invalid_count:
            issues.append(
                f"{col}: {invalid_count} non-numeric value(s)"
            )

        data[col] = converted

        nonfinite = data[col].notna() & ~np.isfinite(data[col])
        if nonfinite.any():
            issues.append(
                f"{col}: {int(nonfinite.sum())} non-finite value(s)"
            )
            data.loc[nonfinite, col] = np.nan

        negative_count = int((data[col] < 0).sum())
        if negative_count:
            issues.append(
                f"{col}: {negative_count} negative value(s)"
            )

    for col in ["quarterly_target", "annual_target"]:
        zero_count = int((data[col] == 0).sum())
        if zero_count:
            issues.append(
                f"{col}: {zero_count} zero target value(s)"
            )

    invalid_period = ~data["reporting_period"].isin(
        ["Q1", "Q2", "Q3", "Q4"]
    )
    if invalid_period.any():
        issues.append(
            f"{int(invalid_period.sum())} invalid reporting period(s)"
        )

    blank_names = (
        data["indicator_name"].isna()
        | data["indicator_name"].astype(str).str.strip().eq("")
    )
    if blank_names.any():
        issues.append(
            f"{int(blank_names.sum())} missing or blank indicator name(s)"
        )

    # Check annual target consistency within each indicator
    inconsistent = data.groupby("indicator_name")[
        "annual_target"
    ].nunique(dropna=True)
    inconsistent_names = inconsistent[inconsistent > 1]

    if len(inconsistent_names):
        issues.append(
            f"{len(inconsistent_names)} indicator(s) have inconsistent "
            "annual targets"
        )

    # Exclude records unsuitable for performance calculations
    valid = (
        ~blank_names
        & data["reporting_period"].isin(["Q1", "Q2", "Q3", "Q4"])
        & data[numeric_columns].notna().all(axis=1)
        & data["quarterly_target"].gt(0)
        & data["annual_target"].gt(0)
        & data["actual"].ge(0)
        & data["quarterly_target"].ge(0)
        & data["annual_target"].ge(0)
    )

    clean = data.loc[valid].copy()

    # Avoid double-counting duplicate indicator-quarter records
    clean = clean.drop_duplicates(
        subset=["indicator_name", "reporting_period"],
        keep=False
    )

    return clean, issues


def analyse_data(data):
    quarterly = data.copy()

    quarterly["achievement_pct"] = (
        quarterly["actual"] / quarterly["quarterly_target"]
    ) * 100

    quarterly["performance_gap"] = (
        quarterly["quarterly_target"] - quarterly["actual"]
    )

    quarterly["performance_status"] = (
        quarterly["achievement_pct"].apply(classify_performance)
    )

    annual = (
        data.groupby("indicator_name", as_index=False)
        .agg(
            annual_target=("annual_target", "first"),
            annual_actual=("actual", "sum"),
            reported_quarters=("reporting_period", "nunique"),
            target_versions=("annual_target", "nunique")
        )
    )

    annual["data_status"] = np.where(
        (annual["reported_quarters"] == 4)
        & (annual["target_versions"] == 1),
        "Complete",
        "Review Required"
    )

    annual["annual_achievement_pct"] = (
        annual["annual_actual"] / annual["annual_target"]
    ) * 100

    annual["annual_performance_gap"] = (
        annual["annual_target"] - annual["annual_actual"]
    )

    annual["performance_status"] = (
        annual["annual_achievement_pct"].apply(classify_performance)
    )

    annual.loc[
        annual["data_status"] != "Complete",
        "performance_status"
    ] = "Review Required"

    return quarterly, annual


# --------------------------------------------------
# Sidebar: dataset selection and navigation
# --------------------------------------------------
st.sidebar.title("MEAL Dashboard")
st.sidebar.caption("Indicator Performance and Data Quality")

uploaded_file = st.sidebar.file_uploader(
    "Upload indicator data",
    type=["csv", "xlsx"]
)

page = st.sidebar.radio(
    "Navigate",
    [
        "Overview",
        "Quarterly Performance",
        "Annual Performance",
        "Data Quality",
        "Follow-up Actions",
        "Download Reports"
    ]
)

if uploaded_file is None:
    raw_data = create_sample_data()
    st.sidebar.info(
        "Showing illustrative sample data. Upload a CSV or Excel file "
        "to analyse your own data."
    )
else:
    try:
        raw_data = load_uploaded_file(uploaded_file)
    except Exception as error:
        st.error(f"Could not read the uploaded file: {error}")
        st.stop()

data, quality_issues = prepare_data(raw_data)

st.title("MEAL Indicator Performance Dashboard")
st.caption(
    "Monitor indicator achievement, identify data-quality concerns, "
    "and support evidence-based programme decisions."
)

if data is None:
    st.error("The uploaded dataset does not have the required columns.")
    st.write("Required columns:", REQUIRED_COLUMNS)
    st.stop()

if data.empty:
    st.error(
        "No valid records are available for analysis. "
        "Review the uploaded data and required columns."
    )
    st.stop()

quarterly, annual = analyse_data(data)

follow_up = quarterly[
    quarterly["performance_status"].isin(
        ["Needs Improvement", "Off Track"]
    )
].copy()

# --------------------------------------------------
# Overview
# --------------------------------------------------
if page == "Overview":
    complete_annual = annual[
        annual["data_status"] == "Complete"
    ]

    average_annual = (
        complete_annual["annual_achievement_pct"].mean()
        if not complete_annual.empty else np.nan
    )

    col1, col2, col3, col4 = st.columns(4)

    col1.metric(
        "Indicators monitored",
        int(data["indicator_name"].nunique())
    )
    col2.metric(
        "Quarterly records",
        int(len(quarterly))
    )
    col3.metric(
        "Average annual achievement",
        f"{average_annual:.1f}%"
        if pd.notna(average_annual) else "N/A"
    )
    col4.metric(
        "Records requiring follow-up",
        int(len(follow_up))
    )

    st.subheader("Quarterly performance trend")

    quarterly_summary = (
        quarterly.groupby("reporting_period", as_index=False)
        .agg(
            average_achievement_pct=("achievement_pct", "mean")
        )
    )

    quarter_order = ["Q1", "Q2", "Q3", "Q4"]
    quarterly_summary["reporting_period"] = pd.Categorical(
        quarterly_summary["reporting_period"],
        categories=quarter_order,
        ordered=True
    )
    quarterly_summary = quarterly_summary.sort_values(
        "reporting_period"
    )

    fig = px.line(
        quarterly_summary,
        x="reporting_period",
        y="average_achievement_pct",
        markers=True,
        title="Average Achievement by Quarter",
        labels={
            "reporting_period": "Quarter",
            "average_achievement_pct": "Average Achievement (%)"
        }
    )
    fig.update_layout(template="plotly_white")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Quarterly performance status")

    status_summary = (
        quarterly.groupby(
            ["reporting_period", "performance_status"]
        )
        .size()
        .reset_index(name="number_of_records")
    )

    fig = px.bar(
        status_summary,
        x="reporting_period",
        y="number_of_records",
        color="performance_status",
        barmode="stack",
        color_discrete_map=STATUS_COLORS,
        category_orders={
            "reporting_period": quarter_order,
            "performance_status": [
                "On Track", "Needs Improvement", "Off Track"
            ]
        },
        labels={
            "reporting_period": "Quarter",
            "number_of_records": "Number of Records",
            "performance_status": "Performance Status"
        }
    )
    fig.update_layout(template="plotly_white")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Annual performance snapshot")
    st.dataframe(
        annual[
            [
                "indicator_name",
                "annual_target",
                "annual_actual",
                "annual_achievement_pct",
                "data_status",
                "performance_status"
            ]
        ].round(2),
        use_container_width=True,
        hide_index=True
    )

# --------------------------------------------------
# Quarterly Performance
# --------------------------------------------------
elif page == "Quarterly Performance":
    st.subheader("Quarterly Indicator Performance")

    selected_quarters = st.multiselect(
        "Select reporting quarters",
        ["Q1", "Q2", "Q3", "Q4"],
        default=["Q1", "Q2", "Q3", "Q4"]
    )

    view = quarterly[
        quarterly["reporting_period"].isin(selected_quarters)
    ].copy()

    fig = px.bar(
        view,
        x="indicator_name",
        y="achievement_pct",
        color="performance_status",
        color_discrete_map=STATUS_COLORS,
        title="Quarterly Achievement by Indicator",
        hover_data=[
            "reporting_period",
            "quarterly_target",
            "actual",
            "performance_gap"
        ],
        labels={
            "indicator_name": "Indicator",
            "achievement_pct": "Achievement (%)",
            "performance_status": "Status"
        }
    )
    fig.add_hline(
        y=90,
        line_dash="dash",
        line_color="green",
        annotation_text="90% threshold"
    )
    fig.update_layout(
        template="plotly_white",
        xaxis_tickangle=-35
    )
    st.plotly_chart(fig, use_container_width=True)

    st.dataframe(
        view[
            [
                "indicator_name", "reporting_period",
                "quarterly_target", "actual", "achievement_pct",
                "performance_gap", "performance_status"
            ]
        ].round(2),
        use_container_width=True,
        hide_index=True
    )

# --------------------------------------------------
# Annual Performance
# --------------------------------------------------
elif page == "Annual Performance":
    st.subheader("Annual Indicator Performance")

    fig = px.bar(
        annual,
        x="indicator_name",
        y="annual_achievement_pct",
        color="performance_status",
        color_discrete_map=STATUS_COLORS,
        hover_data=[
            "annual_target",
            "annual_actual",
            "annual_performance_gap",
            "data_status"
        ],
        title="Annual Achievement Against Targets",
        labels={
            "indicator_name": "Indicator",
            "annual_achievement_pct": "Achievement (%)",
            "performance_status": "Status"
        }
    )
    fig.add_hline(
        y=90,
        line_dash="dash",
        line_color="green",
        annotation_text="90% threshold"
    )
    fig.update_layout(
        template="plotly_white",
        xaxis_tickangle=-35
    )
    st.plotly_chart(fig, use_container_width=True)

    st.dataframe(
        annual.drop(columns=["target_versions"]).round(2),
        use_container_width=True,
        hide_index=True
    )

# --------------------------------------------------
# Data Quality
# --------------------------------------------------
elif page == "Data Quality":
    st.subheader("Data Quality Checks")

    col1, col2 = st.columns(2)
    col1.metric("Uploaded records", len(raw_data))
    col2.metric("Records available for analysis", len(data))

    if quality_issues:
        st.warning(
            "Potential data-quality issues were detected. "
            "Review the findings below before interpreting results."
        )
        for issue in quality_issues:
            st.write(f"- {issue}")
    else:
        st.success(
            "No issues detected by the configured data-quality checks."
        )

    st.markdown(
        "Checks include missing values, duplicate indicator-quarter "
        "records, invalid periods, invalid numeric values, non-positive "
        "targets, negative values, and inconsistent annual targets."
    )

    st.subheader("Data used for analysis")
    st.dataframe(data, use_container_width=True, hide_index=True)

# --------------------------------------------------
# Follow-up Actions
# --------------------------------------------------
elif page == "Follow-up Actions":
    st.subheader("Indicators Requiring Follow-up")

    if follow_up.empty:
        st.success(
            "No quarterly indicators are classified as Needs Improvement "
            "or Off Track in the records available for analysis."
        )
    else:
        st.write(
            "Review these records and document any action taken."
        )
        st.dataframe(
            follow_up[
                [
                    "indicator_name", "reporting_period",
                    "quarterly_target", "actual", "achievement_pct",
                    "performance_gap", "performance_status"
                ]
            ].round(2),
            use_container_width=True,
            hide_index=True
        )

# --------------------------------------------------
# Download Reports
# --------------------------------------------------
elif page == "Download Reports":
    st.subheader("Download MEAL Reports")

    quarterly_csv = quarterly.to_csv(index=False).encode("utf-8")
    annual_csv = annual.to_csv(index=False).encode("utf-8")
    follow_up_csv = follow_up.to_csv(index=False).encode("utf-8")

    summary = pd.DataFrame([
        ["Indicators monitored", data["indicator_name"].nunique()],
        ["Quarterly records analysed", len(quarterly)],
        [
            "Quarterly records On Track",
            int((quarterly["performance_status"] == "On Track").sum())
        ],
        [
            "Quarterly records Needs Improvement",
            int((quarterly["performance_status"] == "Needs Improvement").sum())
        ],
        [
            "Quarterly records Off Track",
            int((quarterly["performance_status"] == "Off Track").sum())
        ],
        ["Data-quality issues detected", len(quality_issues)]
    ], columns=["Measure", "Result"])

    summary_csv = summary.to_csv(index=False).encode("utf-8")

    st.download_button(
        "Download Quarterly Report",
        quarterly_csv,
        file_name="quarterly_meal_report.csv",
        mime="text/csv"
    )

    st.download_button(
        "Download Annual Report",
        annual_csv,
        file_name="annual_meal_report.csv",
        mime="text/csv"
    )

    st.download_button(
        "Download Follow-up Report",
        follow_up_csv,
        file_name="meal_follow_up_report.csv",
        mime="text/csv"
    )

    st.download_button(
        "Download Overall Summary",
        summary_csv,
        file_name="meal_overall_summary.csv",
        mime="text/csv"
    )

st.sidebar.divider()
st.sidebar.caption(
    "Performance rules: On Track ≥90%; Needs Improvement ≥70% "
    "and <90%; Off Track <70%."
)
st.caption(
    "Demonstration dashboard. The performance thresholds are project-defined "
    "and should be agreed with programme stakeholders before operational use."
)

Writing app.py

Validating whether the py file was created

In [ ]:
import os

print("app.py exists:", os.path.exists("app.py"))

if os.path.exists("app.py"):
    print("File size:", os.path.getsize("app.py"), "bytes")

app.py exists: True
File size: 19461 bytes

In [ ]:
import py_compile

py_compile.compile("app.py", doraise=True)
print("Streamlit app syntax check passed.")

Streamlit app syntax check passed.

The code below launches the Streamlit app

In [ ]:
!streamlit run app.py --server.port 8501 --server.headless true > streamlit.log 2>&1 &

In [ ]:
!cat streamlit.log

I will create a public browser accessible link to the streamlit app in the code to install cloudflare tunnel. Please note that the data used throughout development of this MEAL dashboard is fictional.

In [ ]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -O cloudflared.deb
!dpkg -i cloudflared.deb
!cloudflared tunnel --url http://127.0.0.1:8501

Selecting previously unselected package cloudflared.
(Reading database ... 122813 files and directories currently installed.)
Preparing to unpack cloudflared.deb ...
Unpacking cloudflared (2026.10.5) ...
Setting up cloudflared (2026.10.5) ...
Processing triggers for man-db (2.12.0-4build2) ...
2026-10-28T17:12:40Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-10-28T17:12:40Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-10-28T17:12:44Z INF +--------------------------------------------------------------------------------------------+
2026-10-28T17:12:44Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-10-28T17:12:44Z INF |  https://else-toe-copyright-smtp.trycloudflare.com                                         |
2026-10-28T17:12:44Z INF +--------------------------------------------------------------------------------------------+
2026-10-28T17:12:44Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-10-28T17:12:44Z INF Version 2026.10.5 (Checksum e1bc0cf084fd9e590554fe769a86b1db46701c3f847a43d902f7b974a4e16298)
2026-10-28T17:12:44Z INF GOOS: linux, GOVersion: go1.27.3, GoArch: amd64
2026-10-28T17:12:44Z INF Settings: map[ha-connections:1 protocol:quic url:http://127.0.0.1:8501]
2026-10-28T17:12:44Z INF cloudflared will not automatically update if installed by a package manager.
2026-10-28T17:12:44Z INF Generated Connector ID: 70a4ff6c-38f2-4656-af8d-035ed95ddcf3
2026-10-28T17:12:44Z INF Initial protocol quic
2026-10-28T17:12:44Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-10-28T17:12:44Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/10/28 17:12:44 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-10-28T17:12:44Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-10-28T17:12:44Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-10-28T17:12:44Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-10-28T17:12:44Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.13
2026-10-28T17:12:44Z INF Registered tunnel connection connIndex=0 connection=19f17f0e-c720-44dc-8105-c39092bc4636 event=0 ip=198.41.200.13 location=tpe01 protocol=quic
2026-10-28T17:12:50Z INF +-------------------------------------------------------------------------------------+
2026-10-28T17:12:50Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-10-28T17:12:50Z INF +-------------------------------------------------------------------------------------+
2026-10-28T17:12:50Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-10-28T17:12:50Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-10-28T17:12:50Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-10-28T17:12:50Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-10-28T17:12:50Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-10-28T17:12:50Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-10-28T17:12:50Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-10-28T17:12:50Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-10-28T17:12:50Z INF |                                                                                     |
2026-10-28T17:12:50Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-10-28T17:12:50Z INF +-------------------------------------------------------------------------------------+
2026-10-28T17:12:50Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=region1.v2.argotunnel.com
2026-10-28T17:12:50Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=region2.v2.argotunnel.com
2026-10-28T17:12:50Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=region1.v2.argotunnel.com
2026-10-28T17:12:50Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=region2.v2.argotunnel.com
2026-10-28T17:12:50Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=region1.v2.argotunnel.com
2026-10-28T17:12:50Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=region2.v2.argotunnel.com
2026-10-28T17:12:50Z INF precheck component="Cloudflare API" details="API is reachable" run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b status=pass target=api.cloudflare.com:443
2026-10-28T17:12:50Z INF precheck complete hard_fail=false run_id=fc8b7014-17f0-4eeb-b797-c6dcac83320b suggested_protocol=quic